package com.myspace.irsmonitoringdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Job implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "JOB_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "JOB_ID_SEQ", name = "JOB_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Title")
	public java.lang.String title;

	@org.kie.api.definition.type.Label("Status")
	public java.lang.String status;

	@org.kie.api.definition.type.Label(value = "NextJob")
	public java.lang.String nextJob;

	public Job() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getNextJob() {
		return this.nextJob;
	}

	public void setNextJob(java.lang.String nextJob) {
		this.nextJob = nextJob;
	}

	public Job(java.lang.Long id, java.lang.String title,
			java.lang.String status, java.lang.String nextJob) {
		this.id = id;
		this.title = title;
		this.status = status;
		this.nextJob = nextJob;
	}

}